// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdLZdAiHW8I0kEU4NOjcAvITO5F1CUcrk',
    appId: '1:134875107158:web:414ae9b6c2195aedbc50f7',
    messagingSenderId: '134875107158',
    projectId: 'hybridapp-8e623',
    authDomain: 'hybridapp-8e623.firebaseapp.com',
    storageBucket: 'hybridapp-8e623.appspot.com',
    measurementId: 'G-C03L52CHNH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOzsqFxOVljbWmbyigz_45iGxa8AJCQ20',
    appId: '1:134875107158:android:583c6f38c72be5d2bc50f7',
    messagingSenderId: '134875107158',
    projectId: 'hybridapp-8e623',
    storageBucket: 'hybridapp-8e623.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADtek7Xm8W8qRwqVaGzR80E25HbBV159Y',
    appId: '1:134875107158:ios:4b9b2548d8c1cfbabc50f7',
    messagingSenderId: '134875107158',
    projectId: 'hybridapp-8e623',
    storageBucket: 'hybridapp-8e623.appspot.com',
    iosBundleId: 'com.example.nazaria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADtek7Xm8W8qRwqVaGzR80E25HbBV159Y',
    appId: '1:134875107158:ios:4b9b2548d8c1cfbabc50f7',
    messagingSenderId: '134875107158',
    projectId: 'hybridapp-8e623',
    storageBucket: 'hybridapp-8e623.appspot.com',
    iosBundleId: 'com.example.nazaria',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdLZdAiHW8I0kEU4NOjcAvITO5F1CUcrk',
    appId: '1:134875107158:web:d0521ec69f00b9d6bc50f7',
    messagingSenderId: '134875107158',
    projectId: 'hybridapp-8e623',
    authDomain: 'hybridapp-8e623.firebaseapp.com',
    storageBucket: 'hybridapp-8e623.appspot.com',
    measurementId: 'G-342K4D8T1C',
  );
}
